FROM registry

MAINTAINER Joel E White "Joel E White"

ENV REGISTRY_AUTH='htpasswd'
ENV REGISTRY_AUTH_HTPASSWD_REALM='Registry Realm'
ENV REGISTRY_AUTH_HTPASSWD_PATH='/auth/htpasswd'

VOLUME /auth

VOLUME /var/lib/registry

EXPOSE 5000



